services:
  web:
    build: .
    volumes:
      - ./app:/code/app
    ports:
      - "8000:80"
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin