services:
  web:
    build: .
    volumes:
      - ./app:/code/app
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    name: killer_db_data